FROM alpine:3

# membuat folder hello di dalam sistem operasi linux alpine (image)
RUN mkdir hello

# menulis "Hello World" pada file world.txt yg ada di folder hello barusan
RUN echo "Hello World" > "hello/world.txt"

# menampilkan isi dari hello/world.txt pada console linux
RUN cat "hello/world.txt";

